#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBSteem")]
	public partial class steemitDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    #endregion
		
		public steemitDataContext() : 
				base(global::SteemitSQLDBSearch.Properties.Settings.Default.DBSteemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public steemitDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public steemitDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public steemitDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public steemitDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Accounts")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _name;
		
		private string _owner;
		
		private string _active;
		
		private string _posting;
		
		private string _memo_key;
		
		private string _json_metadata;
		
		private string _proxy;
		
		private System.DateTime _last_owner_update;
		
		private System.DateTime _last_account_update;
		
		private System.DateTime _created;
		
		private bool _mined;
		
		private bool _owner_challenged;
		
		private bool _active_challenged;
		
		private System.DateTime _last_owner_proved;
		
		private System.DateTime _last_active_proved;
		
		private string _recovery_account;
		
		private System.DateTime _last_account_recovery;
		
		private string _reset_account;
		
		private long _comment_count;
		
		private long _lifetime_vote_count;
		
		private long _post_count;
		
		private bool _can_vote;
		
		private short _voting_power;
		
		private System.DateTime _last_vote_time;
		
		private string _balance;
		
		private string _savings_balance;
		
		private string _sbd_balance;
		
		private long _sbd_seconds;
		
		private System.DateTime _sbd_seconds_last_update;
		
		private System.DateTime _sbd_last_interest_payment;
		
		private string _savings_sbd_balance;
		
		private long _savings_sbd_seconds;
		
		private System.DateTime _savings_sbd_seconds_last_update;
		
		private System.DateTime _savings_sbd_last_interest_payment;
		
		private int _savings_withdraw_requests;
		
		private string _vesting_shares;
		
		private string _vesting_withdraw_rate;
		
		private System.DateTime _next_vesting_withdrawal;
		
		private long _withdrawn;
		
		private long _to_withdraw;
		
		private short _withdraw_routes;
		
		private long _curation_rewards;
		
		private long _posting_rewards;
		
		private string _proxied_vsf_votes;
		
		private short _witnesses_voted_for;
		
		private long _average_bandwidth;
		
		private long _lifetime_bandwidth;
		
		private System.DateTime _last_bandwidth_update;
		
		private long _average_market_bandwidth;
		
		private System.DateTime _last_market_bandwidth_update;
		
		private System.DateTime _last_post;
		
		private System.DateTime _last_root_post;
		
		private long _post_bandwidth;
		
		private string _vesting_balance;
		
		private string _reputation;
		
		private string _transfer_history;
		
		private string _market_history;
		
		private string _post_history;
		
		private string _vote_history;
		
		private string _other_history;
		
		private string _witness_votes;
		
		private string _blog_category;
		
		private bool _dirty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnownerChanging(string value);
    partial void OnownerChanged();
    partial void OnactiveChanging(string value);
    partial void OnactiveChanged();
    partial void OnpostingChanging(string value);
    partial void OnpostingChanged();
    partial void Onmemo_keyChanging(string value);
    partial void Onmemo_keyChanged();
    partial void Onjson_metadataChanging(string value);
    partial void Onjson_metadataChanged();
    partial void OnproxyChanging(string value);
    partial void OnproxyChanged();
    partial void Onlast_owner_updateChanging(System.DateTime value);
    partial void Onlast_owner_updateChanged();
    partial void Onlast_account_updateChanging(System.DateTime value);
    partial void Onlast_account_updateChanged();
    partial void OncreatedChanging(System.DateTime value);
    partial void OncreatedChanged();
    partial void OnminedChanging(bool value);
    partial void OnminedChanged();
    partial void Onowner_challengedChanging(bool value);
    partial void Onowner_challengedChanged();
    partial void Onactive_challengedChanging(bool value);
    partial void Onactive_challengedChanged();
    partial void Onlast_owner_provedChanging(System.DateTime value);
    partial void Onlast_owner_provedChanged();
    partial void Onlast_active_provedChanging(System.DateTime value);
    partial void Onlast_active_provedChanged();
    partial void Onrecovery_accountChanging(string value);
    partial void Onrecovery_accountChanged();
    partial void Onlast_account_recoveryChanging(System.DateTime value);
    partial void Onlast_account_recoveryChanged();
    partial void Onreset_accountChanging(string value);
    partial void Onreset_accountChanged();
    partial void Oncomment_countChanging(long value);
    partial void Oncomment_countChanged();
    partial void Onlifetime_vote_countChanging(long value);
    partial void Onlifetime_vote_countChanged();
    partial void Onpost_countChanging(long value);
    partial void Onpost_countChanged();
    partial void Oncan_voteChanging(bool value);
    partial void Oncan_voteChanged();
    partial void Onvoting_powerChanging(short value);
    partial void Onvoting_powerChanged();
    partial void Onlast_vote_timeChanging(System.DateTime value);
    partial void Onlast_vote_timeChanged();
    partial void OnbalanceChanging(string value);
    partial void OnbalanceChanged();
    partial void Onsavings_balanceChanging(string value);
    partial void Onsavings_balanceChanged();
    partial void Onsbd_balanceChanging(string value);
    partial void Onsbd_balanceChanged();
    partial void Onsbd_secondsChanging(long value);
    partial void Onsbd_secondsChanged();
    partial void Onsbd_seconds_last_updateChanging(System.DateTime value);
    partial void Onsbd_seconds_last_updateChanged();
    partial void Onsbd_last_interest_paymentChanging(System.DateTime value);
    partial void Onsbd_last_interest_paymentChanged();
    partial void Onsavings_sbd_balanceChanging(string value);
    partial void Onsavings_sbd_balanceChanged();
    partial void Onsavings_sbd_secondsChanging(long value);
    partial void Onsavings_sbd_secondsChanged();
    partial void Onsavings_sbd_seconds_last_updateChanging(System.DateTime value);
    partial void Onsavings_sbd_seconds_last_updateChanged();
    partial void Onsavings_sbd_last_interest_paymentChanging(System.DateTime value);
    partial void Onsavings_sbd_last_interest_paymentChanged();
    partial void Onsavings_withdraw_requestsChanging(int value);
    partial void Onsavings_withdraw_requestsChanged();
    partial void Onvesting_sharesChanging(string value);
    partial void Onvesting_sharesChanged();
    partial void Onvesting_withdraw_rateChanging(string value);
    partial void Onvesting_withdraw_rateChanged();
    partial void Onnext_vesting_withdrawalChanging(System.DateTime value);
    partial void Onnext_vesting_withdrawalChanged();
    partial void OnwithdrawnChanging(long value);
    partial void OnwithdrawnChanged();
    partial void Onto_withdrawChanging(long value);
    partial void Onto_withdrawChanged();
    partial void Onwithdraw_routesChanging(short value);
    partial void Onwithdraw_routesChanged();
    partial void Oncuration_rewardsChanging(long value);
    partial void Oncuration_rewardsChanged();
    partial void Onposting_rewardsChanging(long value);
    partial void Onposting_rewardsChanged();
    partial void Onproxied_vsf_votesChanging(string value);
    partial void Onproxied_vsf_votesChanged();
    partial void Onwitnesses_voted_forChanging(short value);
    partial void Onwitnesses_voted_forChanged();
    partial void Onaverage_bandwidthChanging(long value);
    partial void Onaverage_bandwidthChanged();
    partial void Onlifetime_bandwidthChanging(long value);
    partial void Onlifetime_bandwidthChanged();
    partial void Onlast_bandwidth_updateChanging(System.DateTime value);
    partial void Onlast_bandwidth_updateChanged();
    partial void Onaverage_market_bandwidthChanging(long value);
    partial void Onaverage_market_bandwidthChanged();
    partial void Onlast_market_bandwidth_updateChanging(System.DateTime value);
    partial void Onlast_market_bandwidth_updateChanged();
    partial void Onlast_postChanging(System.DateTime value);
    partial void Onlast_postChanged();
    partial void Onlast_root_postChanging(System.DateTime value);
    partial void Onlast_root_postChanged();
    partial void Onpost_bandwidthChanging(long value);
    partial void Onpost_bandwidthChanged();
    partial void Onvesting_balanceChanging(string value);
    partial void Onvesting_balanceChanged();
    partial void OnreputationChanging(string value);
    partial void OnreputationChanged();
    partial void Ontransfer_historyChanging(string value);
    partial void Ontransfer_historyChanged();
    partial void Onmarket_historyChanging(string value);
    partial void Onmarket_historyChanged();
    partial void Onpost_historyChanging(string value);
    partial void Onpost_historyChanged();
    partial void Onvote_historyChanging(string value);
    partial void Onvote_historyChanged();
    partial void Onother_historyChanging(string value);
    partial void Onother_historyChanged();
    partial void Onwitness_votesChanging(string value);
    partial void Onwitness_votesChanged();
    partial void Onblog_categoryChanging(string value);
    partial void Onblog_categoryChanged();
    partial void OndirtyChanging(bool value);
    partial void OndirtyChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string owner
		{
			get
			{
				return this._owner;
			}
			set
			{
				if ((this._owner != value))
				{
					this.OnownerChanging(value);
					this.SendPropertyChanging();
					this._owner = value;
					this.SendPropertyChanged("owner");
					this.OnownerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posting", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string posting
		{
			get
			{
				return this._posting;
			}
			set
			{
				if ((this._posting != value))
				{
					this.OnpostingChanging(value);
					this.SendPropertyChanging();
					this._posting = value;
					this.SendPropertyChanged("posting");
					this.OnpostingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memo_key", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string memo_key
		{
			get
			{
				return this._memo_key;
			}
			set
			{
				if ((this._memo_key != value))
				{
					this.Onmemo_keyChanging(value);
					this.SendPropertyChanging();
					this._memo_key = value;
					this.SendPropertyChanged("memo_key");
					this.Onmemo_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_json_metadata", DbType="NVarChar(MAX)")]
		public string json_metadata
		{
			get
			{
				return this._json_metadata;
			}
			set
			{
				if ((this._json_metadata != value))
				{
					this.Onjson_metadataChanging(value);
					this.SendPropertyChanging();
					this._json_metadata = value;
					this.SendPropertyChanged("json_metadata");
					this.Onjson_metadataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proxy", DbType="VarChar(50)")]
		public string proxy
		{
			get
			{
				return this._proxy;
			}
			set
			{
				if ((this._proxy != value))
				{
					this.OnproxyChanging(value);
					this.SendPropertyChanging();
					this._proxy = value;
					this.SendPropertyChanged("proxy");
					this.OnproxyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_owner_update", DbType="DateTime NOT NULL")]
		public System.DateTime last_owner_update
		{
			get
			{
				return this._last_owner_update;
			}
			set
			{
				if ((this._last_owner_update != value))
				{
					this.Onlast_owner_updateChanging(value);
					this.SendPropertyChanging();
					this._last_owner_update = value;
					this.SendPropertyChanged("last_owner_update");
					this.Onlast_owner_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_account_update", DbType="DateTime NOT NULL")]
		public System.DateTime last_account_update
		{
			get
			{
				return this._last_account_update;
			}
			set
			{
				if ((this._last_account_update != value))
				{
					this.Onlast_account_updateChanging(value);
					this.SendPropertyChanging();
					this._last_account_update = value;
					this.SendPropertyChanged("last_account_update");
					this.Onlast_account_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime NOT NULL")]
		public System.DateTime created
		{
			get
			{
				return this._created;
			}
			set
			{
				if ((this._created != value))
				{
					this.OncreatedChanging(value);
					this.SendPropertyChanging();
					this._created = value;
					this.SendPropertyChanged("created");
					this.OncreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mined", DbType="Bit NOT NULL")]
		public bool mined
		{
			get
			{
				return this._mined;
			}
			set
			{
				if ((this._mined != value))
				{
					this.OnminedChanging(value);
					this.SendPropertyChanging();
					this._mined = value;
					this.SendPropertyChanged("mined");
					this.OnminedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_challenged", DbType="Bit NOT NULL")]
		public bool owner_challenged
		{
			get
			{
				return this._owner_challenged;
			}
			set
			{
				if ((this._owner_challenged != value))
				{
					this.Onowner_challengedChanging(value);
					this.SendPropertyChanging();
					this._owner_challenged = value;
					this.SendPropertyChanged("owner_challenged");
					this.Onowner_challengedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active_challenged", DbType="Bit NOT NULL")]
		public bool active_challenged
		{
			get
			{
				return this._active_challenged;
			}
			set
			{
				if ((this._active_challenged != value))
				{
					this.Onactive_challengedChanging(value);
					this.SendPropertyChanging();
					this._active_challenged = value;
					this.SendPropertyChanged("active_challenged");
					this.Onactive_challengedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_owner_proved", DbType="DateTime NOT NULL")]
		public System.DateTime last_owner_proved
		{
			get
			{
				return this._last_owner_proved;
			}
			set
			{
				if ((this._last_owner_proved != value))
				{
					this.Onlast_owner_provedChanging(value);
					this.SendPropertyChanging();
					this._last_owner_proved = value;
					this.SendPropertyChanged("last_owner_proved");
					this.Onlast_owner_provedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_active_proved", DbType="DateTime NOT NULL")]
		public System.DateTime last_active_proved
		{
			get
			{
				return this._last_active_proved;
			}
			set
			{
				if ((this._last_active_proved != value))
				{
					this.Onlast_active_provedChanging(value);
					this.SendPropertyChanging();
					this._last_active_proved = value;
					this.SendPropertyChanged("last_active_proved");
					this.Onlast_active_provedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recovery_account", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string recovery_account
		{
			get
			{
				return this._recovery_account;
			}
			set
			{
				if ((this._recovery_account != value))
				{
					this.Onrecovery_accountChanging(value);
					this.SendPropertyChanging();
					this._recovery_account = value;
					this.SendPropertyChanged("recovery_account");
					this.Onrecovery_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_account_recovery", DbType="DateTime NOT NULL")]
		public System.DateTime last_account_recovery
		{
			get
			{
				return this._last_account_recovery;
			}
			set
			{
				if ((this._last_account_recovery != value))
				{
					this.Onlast_account_recoveryChanging(value);
					this.SendPropertyChanging();
					this._last_account_recovery = value;
					this.SendPropertyChanged("last_account_recovery");
					this.Onlast_account_recoveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reset_account", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string reset_account
		{
			get
			{
				return this._reset_account;
			}
			set
			{
				if ((this._reset_account != value))
				{
					this.Onreset_accountChanging(value);
					this.SendPropertyChanging();
					this._reset_account = value;
					this.SendPropertyChanged("reset_account");
					this.Onreset_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment_count", DbType="BigInt NOT NULL")]
		public long comment_count
		{
			get
			{
				return this._comment_count;
			}
			set
			{
				if ((this._comment_count != value))
				{
					this.Oncomment_countChanging(value);
					this.SendPropertyChanging();
					this._comment_count = value;
					this.SendPropertyChanged("comment_count");
					this.Oncomment_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lifetime_vote_count", DbType="BigInt NOT NULL")]
		public long lifetime_vote_count
		{
			get
			{
				return this._lifetime_vote_count;
			}
			set
			{
				if ((this._lifetime_vote_count != value))
				{
					this.Onlifetime_vote_countChanging(value);
					this.SendPropertyChanging();
					this._lifetime_vote_count = value;
					this.SendPropertyChanged("lifetime_vote_count");
					this.Onlifetime_vote_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_count", DbType="BigInt NOT NULL")]
		public long post_count
		{
			get
			{
				return this._post_count;
			}
			set
			{
				if ((this._post_count != value))
				{
					this.Onpost_countChanging(value);
					this.SendPropertyChanging();
					this._post_count = value;
					this.SendPropertyChanged("post_count");
					this.Onpost_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_can_vote", DbType="Bit NOT NULL")]
		public bool can_vote
		{
			get
			{
				return this._can_vote;
			}
			set
			{
				if ((this._can_vote != value))
				{
					this.Oncan_voteChanging(value);
					this.SendPropertyChanging();
					this._can_vote = value;
					this.SendPropertyChanged("can_vote");
					this.Oncan_voteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voting_power", DbType="SmallInt NOT NULL")]
		public short voting_power
		{
			get
			{
				return this._voting_power;
			}
			set
			{
				if ((this._voting_power != value))
				{
					this.Onvoting_powerChanging(value);
					this.SendPropertyChanging();
					this._voting_power = value;
					this.SendPropertyChanged("voting_power");
					this.Onvoting_powerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_vote_time", DbType="DateTime NOT NULL")]
		public System.DateTime last_vote_time
		{
			get
			{
				return this._last_vote_time;
			}
			set
			{
				if ((this._last_vote_time != value))
				{
					this.Onlast_vote_timeChanging(value);
					this.SendPropertyChanging();
					this._last_vote_time = value;
					this.SendPropertyChanged("last_vote_time");
					this.Onlast_vote_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savings_balance", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string savings_balance
		{
			get
			{
				return this._savings_balance;
			}
			set
			{
				if ((this._savings_balance != value))
				{
					this.Onsavings_balanceChanging(value);
					this.SendPropertyChanging();
					this._savings_balance = value;
					this.SendPropertyChanged("savings_balance");
					this.Onsavings_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sbd_balance", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sbd_balance
		{
			get
			{
				return this._sbd_balance;
			}
			set
			{
				if ((this._sbd_balance != value))
				{
					this.Onsbd_balanceChanging(value);
					this.SendPropertyChanging();
					this._sbd_balance = value;
					this.SendPropertyChanged("sbd_balance");
					this.Onsbd_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sbd_seconds", DbType="BigInt NOT NULL")]
		public long sbd_seconds
		{
			get
			{
				return this._sbd_seconds;
			}
			set
			{
				if ((this._sbd_seconds != value))
				{
					this.Onsbd_secondsChanging(value);
					this.SendPropertyChanging();
					this._sbd_seconds = value;
					this.SendPropertyChanged("sbd_seconds");
					this.Onsbd_secondsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sbd_seconds_last_update", DbType="DateTime NOT NULL")]
		public System.DateTime sbd_seconds_last_update
		{
			get
			{
				return this._sbd_seconds_last_update;
			}
			set
			{
				if ((this._sbd_seconds_last_update != value))
				{
					this.Onsbd_seconds_last_updateChanging(value);
					this.SendPropertyChanging();
					this._sbd_seconds_last_update = value;
					this.SendPropertyChanged("sbd_seconds_last_update");
					this.Onsbd_seconds_last_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sbd_last_interest_payment", DbType="DateTime NOT NULL")]
		public System.DateTime sbd_last_interest_payment
		{
			get
			{
				return this._sbd_last_interest_payment;
			}
			set
			{
				if ((this._sbd_last_interest_payment != value))
				{
					this.Onsbd_last_interest_paymentChanging(value);
					this.SendPropertyChanging();
					this._sbd_last_interest_payment = value;
					this.SendPropertyChanged("sbd_last_interest_payment");
					this.Onsbd_last_interest_paymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savings_sbd_balance", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string savings_sbd_balance
		{
			get
			{
				return this._savings_sbd_balance;
			}
			set
			{
				if ((this._savings_sbd_balance != value))
				{
					this.Onsavings_sbd_balanceChanging(value);
					this.SendPropertyChanging();
					this._savings_sbd_balance = value;
					this.SendPropertyChanged("savings_sbd_balance");
					this.Onsavings_sbd_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savings_sbd_seconds", DbType="BigInt NOT NULL")]
		public long savings_sbd_seconds
		{
			get
			{
				return this._savings_sbd_seconds;
			}
			set
			{
				if ((this._savings_sbd_seconds != value))
				{
					this.Onsavings_sbd_secondsChanging(value);
					this.SendPropertyChanging();
					this._savings_sbd_seconds = value;
					this.SendPropertyChanged("savings_sbd_seconds");
					this.Onsavings_sbd_secondsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savings_sbd_seconds_last_update", DbType="DateTime NOT NULL")]
		public System.DateTime savings_sbd_seconds_last_update
		{
			get
			{
				return this._savings_sbd_seconds_last_update;
			}
			set
			{
				if ((this._savings_sbd_seconds_last_update != value))
				{
					this.Onsavings_sbd_seconds_last_updateChanging(value);
					this.SendPropertyChanging();
					this._savings_sbd_seconds_last_update = value;
					this.SendPropertyChanged("savings_sbd_seconds_last_update");
					this.Onsavings_sbd_seconds_last_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savings_sbd_last_interest_payment", DbType="DateTime NOT NULL")]
		public System.DateTime savings_sbd_last_interest_payment
		{
			get
			{
				return this._savings_sbd_last_interest_payment;
			}
			set
			{
				if ((this._savings_sbd_last_interest_payment != value))
				{
					this.Onsavings_sbd_last_interest_paymentChanging(value);
					this.SendPropertyChanging();
					this._savings_sbd_last_interest_payment = value;
					this.SendPropertyChanged("savings_sbd_last_interest_payment");
					this.Onsavings_sbd_last_interest_paymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savings_withdraw_requests", DbType="Int NOT NULL")]
		public int savings_withdraw_requests
		{
			get
			{
				return this._savings_withdraw_requests;
			}
			set
			{
				if ((this._savings_withdraw_requests != value))
				{
					this.Onsavings_withdraw_requestsChanging(value);
					this.SendPropertyChanging();
					this._savings_withdraw_requests = value;
					this.SendPropertyChanged("savings_withdraw_requests");
					this.Onsavings_withdraw_requestsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vesting_shares", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string vesting_shares
		{
			get
			{
				return this._vesting_shares;
			}
			set
			{
				if ((this._vesting_shares != value))
				{
					this.Onvesting_sharesChanging(value);
					this.SendPropertyChanging();
					this._vesting_shares = value;
					this.SendPropertyChanged("vesting_shares");
					this.Onvesting_sharesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vesting_withdraw_rate", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string vesting_withdraw_rate
		{
			get
			{
				return this._vesting_withdraw_rate;
			}
			set
			{
				if ((this._vesting_withdraw_rate != value))
				{
					this.Onvesting_withdraw_rateChanging(value);
					this.SendPropertyChanging();
					this._vesting_withdraw_rate = value;
					this.SendPropertyChanged("vesting_withdraw_rate");
					this.Onvesting_withdraw_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_next_vesting_withdrawal", DbType="DateTime NOT NULL")]
		public System.DateTime next_vesting_withdrawal
		{
			get
			{
				return this._next_vesting_withdrawal;
			}
			set
			{
				if ((this._next_vesting_withdrawal != value))
				{
					this.Onnext_vesting_withdrawalChanging(value);
					this.SendPropertyChanging();
					this._next_vesting_withdrawal = value;
					this.SendPropertyChanged("next_vesting_withdrawal");
					this.Onnext_vesting_withdrawalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_withdrawn", DbType="BigInt NOT NULL")]
		public long withdrawn
		{
			get
			{
				return this._withdrawn;
			}
			set
			{
				if ((this._withdrawn != value))
				{
					this.OnwithdrawnChanging(value);
					this.SendPropertyChanging();
					this._withdrawn = value;
					this.SendPropertyChanged("withdrawn");
					this.OnwithdrawnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_to_withdraw", DbType="BigInt NOT NULL")]
		public long to_withdraw
		{
			get
			{
				return this._to_withdraw;
			}
			set
			{
				if ((this._to_withdraw != value))
				{
					this.Onto_withdrawChanging(value);
					this.SendPropertyChanging();
					this._to_withdraw = value;
					this.SendPropertyChanged("to_withdraw");
					this.Onto_withdrawChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_withdraw_routes", DbType="SmallInt NOT NULL")]
		public short withdraw_routes
		{
			get
			{
				return this._withdraw_routes;
			}
			set
			{
				if ((this._withdraw_routes != value))
				{
					this.Onwithdraw_routesChanging(value);
					this.SendPropertyChanging();
					this._withdraw_routes = value;
					this.SendPropertyChanged("withdraw_routes");
					this.Onwithdraw_routesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curation_rewards", DbType="BigInt NOT NULL")]
		public long curation_rewards
		{
			get
			{
				return this._curation_rewards;
			}
			set
			{
				if ((this._curation_rewards != value))
				{
					this.Oncuration_rewardsChanging(value);
					this.SendPropertyChanging();
					this._curation_rewards = value;
					this.SendPropertyChanged("curation_rewards");
					this.Oncuration_rewardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posting_rewards", DbType="BigInt NOT NULL")]
		public long posting_rewards
		{
			get
			{
				return this._posting_rewards;
			}
			set
			{
				if ((this._posting_rewards != value))
				{
					this.Onposting_rewardsChanging(value);
					this.SendPropertyChanging();
					this._posting_rewards = value;
					this.SendPropertyChanged("posting_rewards");
					this.Onposting_rewardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proxied_vsf_votes", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string proxied_vsf_votes
		{
			get
			{
				return this._proxied_vsf_votes;
			}
			set
			{
				if ((this._proxied_vsf_votes != value))
				{
					this.Onproxied_vsf_votesChanging(value);
					this.SendPropertyChanging();
					this._proxied_vsf_votes = value;
					this.SendPropertyChanged("proxied_vsf_votes");
					this.Onproxied_vsf_votesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_witnesses_voted_for", DbType="SmallInt NOT NULL")]
		public short witnesses_voted_for
		{
			get
			{
				return this._witnesses_voted_for;
			}
			set
			{
				if ((this._witnesses_voted_for != value))
				{
					this.Onwitnesses_voted_forChanging(value);
					this.SendPropertyChanging();
					this._witnesses_voted_for = value;
					this.SendPropertyChanged("witnesses_voted_for");
					this.Onwitnesses_voted_forChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_average_bandwidth", DbType="BigInt NOT NULL")]
		public long average_bandwidth
		{
			get
			{
				return this._average_bandwidth;
			}
			set
			{
				if ((this._average_bandwidth != value))
				{
					this.Onaverage_bandwidthChanging(value);
					this.SendPropertyChanging();
					this._average_bandwidth = value;
					this.SendPropertyChanged("average_bandwidth");
					this.Onaverage_bandwidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lifetime_bandwidth", DbType="BigInt NOT NULL")]
		public long lifetime_bandwidth
		{
			get
			{
				return this._lifetime_bandwidth;
			}
			set
			{
				if ((this._lifetime_bandwidth != value))
				{
					this.Onlifetime_bandwidthChanging(value);
					this.SendPropertyChanging();
					this._lifetime_bandwidth = value;
					this.SendPropertyChanged("lifetime_bandwidth");
					this.Onlifetime_bandwidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_bandwidth_update", DbType="DateTime NOT NULL")]
		public System.DateTime last_bandwidth_update
		{
			get
			{
				return this._last_bandwidth_update;
			}
			set
			{
				if ((this._last_bandwidth_update != value))
				{
					this.Onlast_bandwidth_updateChanging(value);
					this.SendPropertyChanging();
					this._last_bandwidth_update = value;
					this.SendPropertyChanged("last_bandwidth_update");
					this.Onlast_bandwidth_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_average_market_bandwidth", DbType="BigInt NOT NULL")]
		public long average_market_bandwidth
		{
			get
			{
				return this._average_market_bandwidth;
			}
			set
			{
				if ((this._average_market_bandwidth != value))
				{
					this.Onaverage_market_bandwidthChanging(value);
					this.SendPropertyChanging();
					this._average_market_bandwidth = value;
					this.SendPropertyChanged("average_market_bandwidth");
					this.Onaverage_market_bandwidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_market_bandwidth_update", DbType="DateTime NOT NULL")]
		public System.DateTime last_market_bandwidth_update
		{
			get
			{
				return this._last_market_bandwidth_update;
			}
			set
			{
				if ((this._last_market_bandwidth_update != value))
				{
					this.Onlast_market_bandwidth_updateChanging(value);
					this.SendPropertyChanging();
					this._last_market_bandwidth_update = value;
					this.SendPropertyChanged("last_market_bandwidth_update");
					this.Onlast_market_bandwidth_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_post", DbType="DateTime NOT NULL")]
		public System.DateTime last_post
		{
			get
			{
				return this._last_post;
			}
			set
			{
				if ((this._last_post != value))
				{
					this.Onlast_postChanging(value);
					this.SendPropertyChanging();
					this._last_post = value;
					this.SendPropertyChanged("last_post");
					this.Onlast_postChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_root_post", DbType="DateTime NOT NULL")]
		public System.DateTime last_root_post
		{
			get
			{
				return this._last_root_post;
			}
			set
			{
				if ((this._last_root_post != value))
				{
					this.Onlast_root_postChanging(value);
					this.SendPropertyChanging();
					this._last_root_post = value;
					this.SendPropertyChanged("last_root_post");
					this.Onlast_root_postChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_bandwidth", DbType="BigInt NOT NULL")]
		public long post_bandwidth
		{
			get
			{
				return this._post_bandwidth;
			}
			set
			{
				if ((this._post_bandwidth != value))
				{
					this.Onpost_bandwidthChanging(value);
					this.SendPropertyChanging();
					this._post_bandwidth = value;
					this.SendPropertyChanged("post_bandwidth");
					this.Onpost_bandwidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vesting_balance", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string vesting_balance
		{
			get
			{
				return this._vesting_balance;
			}
			set
			{
				if ((this._vesting_balance != value))
				{
					this.Onvesting_balanceChanging(value);
					this.SendPropertyChanging();
					this._vesting_balance = value;
					this.SendPropertyChanged("vesting_balance");
					this.Onvesting_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reputation", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string reputation
		{
			get
			{
				return this._reputation;
			}
			set
			{
				if ((this._reputation != value))
				{
					this.OnreputationChanging(value);
					this.SendPropertyChanging();
					this._reputation = value;
					this.SendPropertyChanged("reputation");
					this.OnreputationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transfer_history", DbType="VarChar(MAX)")]
		public string transfer_history
		{
			get
			{
				return this._transfer_history;
			}
			set
			{
				if ((this._transfer_history != value))
				{
					this.Ontransfer_historyChanging(value);
					this.SendPropertyChanging();
					this._transfer_history = value;
					this.SendPropertyChanged("transfer_history");
					this.Ontransfer_historyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_market_history", DbType="VarChar(MAX)")]
		public string market_history
		{
			get
			{
				return this._market_history;
			}
			set
			{
				if ((this._market_history != value))
				{
					this.Onmarket_historyChanging(value);
					this.SendPropertyChanging();
					this._market_history = value;
					this.SendPropertyChanged("market_history");
					this.Onmarket_historyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_history", DbType="VarChar(MAX)")]
		public string post_history
		{
			get
			{
				return this._post_history;
			}
			set
			{
				if ((this._post_history != value))
				{
					this.Onpost_historyChanging(value);
					this.SendPropertyChanging();
					this._post_history = value;
					this.SendPropertyChanged("post_history");
					this.Onpost_historyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vote_history", DbType="VarChar(MAX)")]
		public string vote_history
		{
			get
			{
				return this._vote_history;
			}
			set
			{
				if ((this._vote_history != value))
				{
					this.Onvote_historyChanging(value);
					this.SendPropertyChanging();
					this._vote_history = value;
					this.SendPropertyChanged("vote_history");
					this.Onvote_historyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other_history", DbType="VarChar(MAX)")]
		public string other_history
		{
			get
			{
				return this._other_history;
			}
			set
			{
				if ((this._other_history != value))
				{
					this.Onother_historyChanging(value);
					this.SendPropertyChanging();
					this._other_history = value;
					this.SendPropertyChanged("other_history");
					this.Onother_historyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_witness_votes", DbType="VarChar(MAX)")]
		public string witness_votes
		{
			get
			{
				return this._witness_votes;
			}
			set
			{
				if ((this._witness_votes != value))
				{
					this.Onwitness_votesChanging(value);
					this.SendPropertyChanging();
					this._witness_votes = value;
					this.SendPropertyChanged("witness_votes");
					this.Onwitness_votesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blog_category", DbType="VarChar(MAX)")]
		public string blog_category
		{
			get
			{
				return this._blog_category;
			}
			set
			{
				if ((this._blog_category != value))
				{
					this.Onblog_categoryChanging(value);
					this.SendPropertyChanging();
					this._blog_category = value;
					this.SendPropertyChanged("blog_category");
					this.Onblog_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dirty", DbType="Bit NOT NULL")]
		public bool dirty
		{
			get
			{
				return this._dirty;
			}
			set
			{
				if ((this._dirty != value))
				{
					this.OndirtyChanging(value);
					this.SendPropertyChanging();
					this._dirty = value;
					this.SendPropertyChanged("dirty");
					this.OndirtyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
