//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string id { get; set; }
        public string name { get; set; }
        public string owner { get; set; }
        public string active { get; set; }
        public string posting { get; set; }
        public string memo_key { get; set; }
        public string json_metadata { get; set; }
        public string proxy { get; set; }
        public System.DateTime last_owner_update { get; set; }
        public System.DateTime last_account_update { get; set; }
        public System.DateTime created { get; set; }
        public bool mined { get; set; }
        public bool owner_challenged { get; set; }
        public bool active_challenged { get; set; }
        public System.DateTime last_owner_proved { get; set; }
        public System.DateTime last_active_proved { get; set; }
        public string recovery_account { get; set; }
        public System.DateTime last_account_recovery { get; set; }
        public string reset_account { get; set; }
        public long comment_count { get; set; }
        public long lifetime_vote_count { get; set; }
        public long post_count { get; set; }
        public bool can_vote { get; set; }
        public short voting_power { get; set; }
        public System.DateTime last_vote_time { get; set; }
        public string balance { get; set; }
        public string savings_balance { get; set; }
        public string sbd_balance { get; set; }
        public long sbd_seconds { get; set; }
        public System.DateTime sbd_seconds_last_update { get; set; }
        public System.DateTime sbd_last_interest_payment { get; set; }
        public string savings_sbd_balance { get; set; }
        public long savings_sbd_seconds { get; set; }
        public System.DateTime savings_sbd_seconds_last_update { get; set; }
        public System.DateTime savings_sbd_last_interest_payment { get; set; }
        public int savings_withdraw_requests { get; set; }
        public string vesting_shares { get; set; }
        public string vesting_withdraw_rate { get; set; }
        public System.DateTime next_vesting_withdrawal { get; set; }
        public long withdrawn { get; set; }
        public long to_withdraw { get; set; }
        public short withdraw_routes { get; set; }
        public long curation_rewards { get; set; }
        public long posting_rewards { get; set; }
        public string proxied_vsf_votes { get; set; }
        public short witnesses_voted_for { get; set; }
        public long average_bandwidth { get; set; }
        public long lifetime_bandwidth { get; set; }
        public System.DateTime last_bandwidth_update { get; set; }
        public long average_market_bandwidth { get; set; }
        public System.DateTime last_market_bandwidth_update { get; set; }
        public System.DateTime last_post { get; set; }
        public System.DateTime last_root_post { get; set; }
        public long post_bandwidth { get; set; }
        public string vesting_balance { get; set; }
        public string reputation { get; set; }
        public string transfer_history { get; set; }
        public string market_history { get; set; }
        public string post_history { get; set; }
        public string vote_history { get; set; }
        public string other_history { get; set; }
        public string witness_votes { get; set; }
        public string blog_category { get; set; }
        public bool dirty { get; set; }
    }
}
