//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.TxAccountCreates = new HashSet<TxAccountCreate>();
            this.TxAccountRecovers = new HashSet<TxAccountRecover>();
            this.TxAccountUpdates = new HashSet<TxAccountUpdate>();
            this.TxAccountWitnessProxies = new HashSet<TxAccountWitnessProxy>();
            this.TxAccountWitnessVotes = new HashSet<TxAccountWitnessVote>();
            this.TxClaimRewardBalances = new HashSet<TxClaimRewardBalance>();
            this.TxCommentsOptions = new HashSet<TxCommentsOption>();
            this.TxConverts = new HashSet<TxConvert>();
            this.TxCustoms = new HashSet<TxCustom>();
            this.TxDelegateVestingShares = new HashSet<TxDelegateVestingShare>();
            this.TxDeleteComments = new HashSet<TxDeleteComment>();
            this.TxEscrowApproves = new HashSet<TxEscrowApprove>();
            this.TxEscrowDisputes = new HashSet<TxEscrowDispute>();
            this.TxEscrowReleases = new HashSet<TxEscrowReleas>();
            this.TxEscrowTransfers = new HashSet<TxEscrowTransfer>();
            this.TxFeeds = new HashSet<TxFeed>();
            this.TxLimitOrders = new HashSet<TxLimitOrder>();
            this.TxPows = new HashSet<TxPow>();
            this.TxTransfers = new HashSet<TxTransfer>();
            this.TxVotes = new HashSet<TxVote>();
            this.TxWitnessUpdates = new HashSet<TxWitnessUpdate>();
            this.TxWithdraws = new HashSet<TxWithdraw>();
            this.TxWithdrawVestingRoutes = new HashSet<TxWithdrawVestingRoute>();
        }
    
        public int tx_id { get; set; }
        public int block_num { get; set; }
        public byte transaction_num { get; set; }
        public int ref_block_num { get; set; }
        public long ref_block_prefix { get; set; }
        public System.DateTime expiration { get; set; }
        public string type { get; set; }
    
        public virtual Block Block { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxAccountCreate> TxAccountCreates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxAccountRecover> TxAccountRecovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxAccountUpdate> TxAccountUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxAccountWitnessProxy> TxAccountWitnessProxies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxAccountWitnessVote> TxAccountWitnessVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxClaimRewardBalance> TxClaimRewardBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxCommentsOption> TxCommentsOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxConvert> TxConverts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxCustom> TxCustoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxDelegateVestingShare> TxDelegateVestingShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxDeleteComment> TxDeleteComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxEscrowApprove> TxEscrowApproves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxEscrowDispute> TxEscrowDisputes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxEscrowReleas> TxEscrowReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxEscrowTransfer> TxEscrowTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxFeed> TxFeeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxLimitOrder> TxLimitOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxPow> TxPows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxTransfer> TxTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxVote> TxVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxWitnessUpdate> TxWitnessUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxWithdraw> TxWithdraws { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxWithdrawVestingRoute> TxWithdrawVestingRoutes { get; set; }
    }
}
