//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxAccountUpdate
    {
        public int ID { get; set; }
        public int tx_id { get; set; }
        public string account { get; set; }
        public string key_auth1 { get; set; }
        public string key_auth2 { get; set; }
        public string memo_key { get; set; }
        public string json_metadata { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
