//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxAccountCreate
    {
        public int ID { get; set; }
        public int tx_id { get; set; }
        public decimal fee { get; set; }
        public decimal delegation { get; set; }
        public string creator { get; set; }
        public string new_account_name { get; set; }
        public string owner_key { get; set; }
        public string active_key { get; set; }
        public string posting_key { get; set; }
        public string memo_key { get; set; }
        public string json_metadata { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
