//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxCommentsOption
    {
        public int ID { get; set; }
        public int tx_id { get; set; }
        public string author { get; set; }
        public string permlink { get; set; }
        public decimal max_accepted_payout { get; set; }
        public short percent_steem_dollars { get; set; }
        public bool allow_votes { get; set; }
        public bool allow_curation_rewards { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
