//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxCustomsFollow
    {
        public System.DateTime timestamp { get; set; }
        public string follower { get; set; }
        public string following { get; set; }
        public string what { get; set; }
    }
}
