//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxCustomsReblog
    {
        public System.DateTime timestamp { get; set; }
        public string account { get; set; }
        public string author { get; set; }
        public string permlink { get; set; }
    }
}
