//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxLimitOrder
    {
        public int ID { get; set; }
        public int tx_id { get; set; }
        public string owner { get; set; }
        public long orderid { get; set; }
        public bool cancel { get; set; }
        public Nullable<decimal> amount_to_sell { get; set; }
        public Nullable<decimal> min_to_receive { get; set; }
        public bool fill_or_kill { get; set; }
        public Nullable<System.DateTime> expiration { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
