//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxWitnessUpdate
    {
        public int ID { get; set; }
        public int tx_id { get; set; }
        public string owner { get; set; }
        public string url { get; set; }
        public string block_signing_key { get; set; }
        public decimal props_account_creation_fee { get; set; }
        public int props_maximum_block_size { get; set; }
        public int props_sbd_interest_rate { get; set; }
        public decimal fee { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
