//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteemitSQLDBSearch.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOFillVestingWithdraw
    {
        public int ID { get; set; }
        public int block_num { get; set; }
        public System.DateTime timestamp { get; set; }
        public string from_account { get; set; }
        public string to_account { get; set; }
        public string withdrawn { get; set; }
        public string deposited { get; set; }
    
        public virtual Block Block { get; set; }
    }
}
